name: automated_script_builder
description: "Flutter Package to record all of user interaction in one external file."
version: 1.3.9
publish_to: none

environment:
  sdk: '>=3.5.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  lite_storage: ^1.0.0
  path_provider:
  permission_handler:

dev_dependencies:
  flutter_lints:
