name: automated_script_builder
description: "Flutter Package to record all of user interaction in one external file."
version: 1.3.7
publish_to: none

environment:
  sdk: '>=3.5.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  path_provider:
  permission_handler:

  lite_storage:
    git: https://github.com/ArZHa03/lite_storage.git


dev_dependencies:
  flutter_lints:
