name: automated_script_builder
description: "Flutter Package to record all of user interaction in one external file."
version: 0.1.3

environment:
  sdk: '>=3.3.4'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
