name: automated_script_builder
description: "Flutter Package to record all of user interaction in one external file."
version: 0.1.3
publish_to: none

environment:
  sdk: '>=3.3.4'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0

  lite_storage:
    git: https://github.com/ArZHa03/lite_storage.git


dev_dependencies:
  flutter_lints: ^5.0.0
